# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding_programs\PythonPrograms\student_status_information\admin_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from admin_ui import Ui_admin_data_manage,Ui_admin_grad_manage,Ui_admin_grade_analyze, Ui_admin_stu_grades,Ui_admin_stu_info,Ui_admin_sys_auth_manage
import sys

class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1124, 849)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\coding_programs\\PythonPrograms\\student_status_information\\login_ui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login.setWindowIcon(icon)
        self.stu_info_Button = QtWidgets.QPushButton(login)
        self.stu_info_Button.setGeometry(QtCore.QRect(450, 60, 151, 91))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.stu_info_Button.setFont(font)
        self.stu_info_Button.setObjectName("stu_info_Button")
        self.stu_info_Button.clicked.connect(self.adm_stu_info)
        self.stu_grade_Button = QtWidgets.QPushButton(login)
        self.stu_grade_Button.setGeometry(QtCore.QRect(450, 190, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.stu_grade_Button.setFont(font)
        self.stu_grade_Button.setObjectName("stu_grade_Button")
        self.stu_grade_Button.clicked.connect(self.adm_stu_grades)
        self.grad_manage_Button = QtWidgets.QPushButton(login)
        self.grad_manage_Button.setGeometry(QtCore.QRect(450, 410, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.grad_manage_Button.setFont(font)
        self.grad_manage_Button.setObjectName("grad_manage_Button")
        self.grad_manage_Button.clicked.connect(self.adm_grade_man)
        self.sys_restore_Button = QtWidgets.QPushButton(login)
        self.sys_restore_Button.setGeometry(QtCore.QRect(450, 530, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.sys_restore_Button.setFont(font)
        self.sys_restore_Button.setObjectName("sys_restore_Button")
        self.sys_restore_Button.clicked.connect(self.adm_data_man)
        self.grade_analyse_Button = QtWidgets.QPushButton(login)
        self.grade_analyse_Button.setGeometry(QtCore.QRect(450, 300, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.grade_analyse_Button.setFont(font)
        self.grade_analyse_Button.setObjectName("grade_analyse_Button")
        self.grade_analyse_Button.clicked.connect(self.adm_grade_ana)
        self.sys_auth_Button = QtWidgets.QPushButton(login)
        self.sys_auth_Button.setGeometry(QtCore.QRect(450, 650, 151, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        self.sys_auth_Button.setFont(font)
        self.sys_auth_Button.setObjectName("sys_auth_Button")
        self.sys_auth_Button.clicked.connect(self.adm_sys_auth)

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "管理信息入口"))
        self.stu_info_Button.setText(_translate("login", "学生信息管理"))
        self.stu_grade_Button.setText(_translate("login", "学生成绩管理"))
        self.grad_manage_Button.setText(_translate("login", "毕业管理"))
        self.sys_restore_Button.setText(_translate("login", "系统维护"))
        self.grade_analyse_Button.setText(_translate("login", "成绩分析"))
        self.sys_auth_Button.setText(_translate("login", "权限管理"))


    def adm_stu_info(self):
        self.adm_stu_info_MainWindow = QtWidgets.QMainWindow()
        self.adm_stu_info_window = Ui_admin_stu_info.Ui_login()
        self.adm_stu_info_window.setupUi(self.adm_stu_info_MainWindow)
        self.adm_stu_info_MainWindow.show()
    
    def adm_stu_grades(self):
        self.adm_stu_grades_MainWindow=QtWidgets.QMainWindow()
        self.adm_stu_grades_window=Ui_admin_stu_grades.Ui_login()
        self.adm_stu_grades_window.setupUi(self.adm_stu_grades_MainWindow)
        self.adm_stu_grades_MainWindow.show()

    def adm_grade_man(self):
        self.adm_grade_man_MainWindow = QtWidgets.QMainWindow()
        self.adm_grade_man_window = Ui_admin_grad_manage.Ui_login()
        self.adm_grade_man_window.setupUi(self.adm_grade_man_MainWindow)
        self.adm_grade_man_MainWindow.show()
    
    def adm_grade_ana(self):
        self.adm_grade_ana_MainWindow = QtWidgets.QMainWindow()
        self.adm_grade_ana_window = Ui_admin_grade_analyze.Ui_login()
        self.adm_grade_ana_window.setupUi(self.adm_grade_ana_MainWindow)
        self.adm_grade_ana_MainWindow.show()
    
    def adm_data_man(self):
        self.adm_data_man_MainWindow = QtWidgets.QMainWindow()
        self.adm_data_man_window = Ui_admin_data_manage.Ui_login()
        self.adm_data_man_window.setupUi(self.adm_data_man_MainWindow)
        self.adm_data_man_MainWindow.show()
    
    def adm_sys_auth(self):
        self.adm_sys_auth_MainWindow = QtWidgets.QMainWindow()
        self.adm_sys_auth_window = Ui_admin_sys_auth_manage.Ui_login()
        self.adm_sys_auth_window.setupUi(self.adm_sys_auth_MainWindow)
        self.adm_sys_auth_MainWindow.show()

if __name__=='__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    login_ui = Ui_login()
    login_ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())