'''
Description: 
Author: dive668
Date: 2021-07-20 10:59:01
LastEditTime: 2021-07-22 16:44:40
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding_programs\PythonPrograms\student_status_information\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import hashlib
import pymysql
from pymysql.err import Error
import Ui_stu_main_window
import Ui_admin_main_window
class Ui_login(object):

    def __init__(self):
        pass
    
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1123, 849)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\coding_programs\\PythonPrograms\\student_status_information\\login_ui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login.setWindowIcon(icon)
        self.passwd_label = QtWidgets.QLabel(login)
        self.passwd_label.setGeometry(QtCore.QRect(370, 420, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.passwd_label.setFont(font)
        self.passwd_label.setObjectName("passwd_label")
        self.passwd_lineEdit = QtWidgets.QLineEdit(login)
        self.passwd_lineEdit.setGeometry(QtCore.QRect(490, 430, 211, 51))
        self.passwd_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwd_lineEdit.setObjectName("passwd_lineEdit")
        self.stu_login_Button = QtWidgets.QPushButton(login)
        self.stu_login_Button.setGeometry(QtCore.QRect(360, 510, 131, 61))
        self.stu_login_Button.setObjectName("stu_login_Button")
        self.stu_login_Button.clicked.connect(self.stu_login)
        self.admin_teach_login_Button = QtWidgets.QPushButton(login)
        self.admin_teach_login_Button.setGeometry(QtCore.QRect(570, 510, 141, 61))
        self.admin_teach_login_Button.setObjectName("admin_teach_login_Button")
        self.admin_teach_login_Button.clicked.connect(self.adm_login)
        self.user_label = QtWidgets.QLabel(login)
        self.user_label.setGeometry(QtCore.QRect(370, 330, 131, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.user_label.setFont(font)
        self.user_label.setObjectName("user_label")
        self.user_lineEdit = QtWidgets.QLineEdit(login)
        self.user_lineEdit.setGeometry(QtCore.QRect(490, 350, 211, 51))
        self.user_lineEdit.setObjectName("user_lineEdit")
        self.software_title = QtWidgets.QLabel(login)
        self.software_title.setGeometry(QtCore.QRect(300, 150, 491, 161))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        self.software_title.setFont(font)
        self.software_title.setObjectName("software_title")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "学生学籍信息管理系统"))
        self.passwd_label.setText(_translate("login", "密  码："))
        self.stu_login_Button.setText(_translate("login", "学生登录"))
        self.admin_teach_login_Button.setText(_translate("login", "教师/管理员登录"))
        self.user_label.setText(_translate("login", "用户名："))
        self.software_title.setText(_translate("login", "学生学籍信息管理系统"))

    def generateMD5(self,str):
        h=hashlib.md5()
        h.update(str.encode(encoding='utf-8'))
        return h.hexdigest()
    
    #点击学生登录的跳转
    def stu_login(self):
        stu_user=self.user_lineEdit.text().strip()
        stu_passwd=self.passwd_lineEdit.text().strip()   
        hex_stu_passwd=self.generateMD5(stu_passwd)
        try:
            db=pymysql.connect(host='127.0.0.1',user="student",password="123456",database="student_status_information")
            cursor=db.cursor()
            cursor.execute("select stu_user_id,stu_password from stu_users where stu_user_id=%s and stu_password=%s",(stu_user,hex_stu_passwd))
            results=cursor.fetchall()
            if results==(): #注意没有匹配到结果的返回值是()
                self.login_msg_error = QtWidgets.QMessageBox()
                self.login_msg_error.setText("账号/密码存在错误，请重新输入")
                self.login_msg_error.show()
                self.user_lineEdit.clear()
                self.passwd_lineEdit.clear()
                self.user_lineEdit.setFocus()
            else:
                MainWindow.close()
                self.stu_MainWindow = QtWidgets.QMainWindow()
                self.stu_main_window = Ui_stu_main_window.Ui_login()
                self.stu_main_window.setupUi(self.stu_MainWindow)
                self.stu_main_window.welcome_lineEdit.setText(stu_user)
                self.stu_main_window.welcome_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
                self.stu_main_window.welcome_lineEdit.setEnabled(False)#无法获得焦点，自然无法输入，其他文本控件类似 
                self.stu_MainWindow.show()
            db.close()
        except:
            Error_msg=QtWidgets.QMessageBox()
            Error_msg.setText("MYSQL服务未连接")
            Error_msg.show()


    #点击管理登录的跳转
    def adm_login(self):
        adm_user=self.user_lineEdit.text().strip()
        adm_passwd=self.passwd_lineEdit.text().strip()
        hex_adm_passwd=self.generateMD5(adm_passwd)
        try:
            db=pymysql.connect(host='127.0.0.1',user="root",password="123456",database="student_status_information")
            cursor=db.cursor()
            cursor.execute("select adm_user_id,adm_password from adm_users where adm_user_id=%s and adm_password=%s",(adm_user,hex_adm_passwd))
            results=cursor.fetchall()
            print(results)
            if results==():
                self.login_msg_error=QtWidgets.QMessageBox()
                self.login_msg_error.setText("账号/密码存在错误，请重新输入")
                self.login_msg_error.show()
                self.user_lineEdit.clear()
                self.passwd_lineEdit.clear()
                self.user_lineEdit.setFocus()
            else:
                MainWindow.close()
                self.adm_MainWindow=QtWidgets.QMainWindow()
                self.adm_main_window=Ui_admin_main_window.Ui_login()
                self.adm_main_window.setupUi(self.adm_MainWindow)
                self.adm_MainWindow.show()
            db.close()
        except:
            Error_msg=QtWidgets.QMessageBox()
            Error_msg.setText("MYSQL服务未连接")
            Error_msg.show()

if __name__=='__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    login_ui = Ui_login()
    login_ui.setupUi(MainWindow)
    login_ui.user_lineEdit.setFocus()
    MainWindow.show()
    sys.exit(app.exec_())