'''
Description: 
Author: dive668
Date: 2021-07-22 08:28:06
LastEditTime: 2021-07-22 10:48:25
'''
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding_programs\PythonPrograms\student_status_information\stu_main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from student_ui import Ui_stu_grades,Ui_stu_information

class Ui_login(object):
    
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1121, 850)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\coding_programs\\PythonPrograms\\student_status_information\\login_ui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login.setWindowIcon(icon)
        self.self_info_Button = QtWidgets.QPushButton(login)
        self.self_info_Button.setGeometry(QtCore.QRect(320, 220, 431, 131))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.self_info_Button.setFont(font)
        self.self_info_Button.setObjectName("self_info_Button")
        self.self_info_Button.clicked.connect(self.stu_self_info)
        self.self_grade_Button = QtWidgets.QPushButton(login)
        self.self_grade_Button.setGeometry(QtCore.QRect(320, 440, 431, 121))
        self.self_grade_Button.clicked.connect(self.stu_self_grades)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.self_grade_Button.setFont(font)
        self.self_grade_Button.setObjectName("self_grade_Button")
        self.welcome_lineEdit = QtWidgets.QLineEdit(login)
        self.welcome_lineEdit.setGeometry(QtCore.QRect(220, 80, 631, 81))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.welcome_lineEdit.setFont(font)
        self.welcome_lineEdit.setObjectName("welcome_lineEdit")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "学生信息入口"))
        self.self_info_Button.setText(_translate("login", "个人信息"))
        self.self_grade_Button.setText(_translate("login", "个人成绩"))

    def stu_self_info(self):
        self.stu_info_MainWindow = QtWidgets.QMainWindow()
        self.stu_info_window = Ui_stu_information.Ui_login()
        self.stu_info_window.setupUi(self.stu_info_MainWindow)
        self.stu_info_window.sno_lineEdit.setText(self.welcome_lineEdit.text())
        self.stu_info_window.sno_lineEdit.setEnabled(False)
        self.stu_info_MainWindow.show()
    
    def stu_self_grades(self):
        self.stu_grades_MainWindow=QtWidgets.QMainWindow()
        self.stu_grades_window=Ui_stu_grades.Ui_login()
        self.stu_grades_window.setupUi(self.stu_grades_MainWindow)
        self.stu_grades_window.stu_id_lineEdit.setText(self.welcome_lineEdit.text())
        self.stu_grades_window.stu_id_lineEdit.setEnabled(False)
        self.stu_grades_MainWindow.show()