# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\coding_programs\PythonPrograms\student_status_information\student_ui\stu_grades.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pymysql
import sys
class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(1124, 849)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\coding_programs\\PythonPrograms\\student_status_information\\student_ui\\login_ui.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        login.setWindowIcon(icon)
        self.select_all_Button = QtWidgets.QPushButton(login)
        self.select_all_Button.setGeometry(QtCore.QRect(280, 680, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.select_all_Button.setFont(font)
        self.select_all_Button.setObjectName("select_all_Button")
        self.select_all_Button.clicked.connect(self.show_stu_all_grades)
        self.select_Button = QtWidgets.QPushButton(login)
        self.select_Button.setGeometry(QtCore.QRect(770, 680, 141, 61))
        self.select_Button.clicked.connect(self.show_stu_spec_grade)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.select_Button.setFont(font)
        self.select_Button.setObjectName("select_Button")
        self.cour_name_label = QtWidgets.QLabel(login)
        self.cour_name_label.setGeometry(QtCore.QRect(50, 270, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.learn_sem_label = QtWidgets.QLabel(login)
        self.learn_sem_label.setGeometry(QtCore.QRect(80, 360, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.learn_sem_label.setFont(font)
        self.learn_sem_label.setObjectName("learn_sem_label")
        self.learn_year_label = QtWidgets.QLabel(login)
        self.learn_year_label.setGeometry(QtCore.QRect(80, 470, 121, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.learn_year_label.setFont(font)
        self.learn_year_label.setObjectName("learn_year_label")
        self.stu_grad_tableWidget = QtWidgets.QTableWidget(login)
        self.stu_grad_tableWidget.setGeometry(QtCore.QRect(490, 110, 591, 491))
        self.stu_grad_tableWidget.setObjectName("stu_grad_tableWidget")
        self.stu_grad_tableWidget.setColumnCount(7) #一定要修改不然出问题
        self.stu_grad_tableWidget.setRowCount(0) 
        self.stu_grad_tableWidget.setHorizontalHeaderLabels(["学号","姓名","课程号","课程名","学期","学年","成绩"])
        self.learn_sem_comboBox = QtWidgets.QComboBox(login)
        self.learn_sem_comboBox.setGeometry(QtCore.QRect(200, 370, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.learn_sem_comboBox.setFont(font)
        self.learn_sem_comboBox.setObjectName("learn_sem_comboBox")
        self.learn_sem_comboBox.addItem("")
        self.learn_sem_comboBox.addItem("")
        self.learn_sem_comboBox.addItem("")
        self.learn_year_comboBox = QtWidgets.QComboBox(login)
        self.learn_year_comboBox.setGeometry(QtCore.QRect(200, 480, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.learn_year_comboBox.setFont(font)
        self.learn_year_comboBox.setObjectName("learn_year_comboBox")
        self.learn_year_comboBox.addItem("")
        self.learn_year_comboBox.addItem("")
        self.learn_year_comboBox.addItem("")
        self.learn_year_comboBox.addItem("")
        self.learn_year_comboBox.addItem("")
        self.stu_id_lineEdit = QtWidgets.QLineEdit(login)
        self.stu_id_lineEdit.setGeometry(QtCore.QRect(200, 180, 211, 51))
        self.stu_id_lineEdit.setText("")
        self.stu_id_lineEdit.setObjectName("stu_id_lineEdit")
        self.stu_id_label = QtWidgets.QLabel(login)
        self.stu_id_label.setGeometry(QtCore.QRect(80, 170, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.stu_id_label.setFont(font)
        self.stu_id_label.setObjectName("stu_id_label")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "学生个人成绩查询"))
        self.select_all_Button.setText(_translate("login", "遍历"))
        self.select_Button.setText(_translate("login", "查询"))
        self.learn_sem_label.setText(_translate("login", "学期："))
        self.learn_year_label.setText(_translate("login", "学年："))
        self.learn_sem_comboBox.setItemText(0, _translate("login", "全部"))
        self.learn_sem_comboBox.setItemText(1, _translate("login", "春季"))
        self.learn_sem_comboBox.setItemText(2, _translate("login", "秋季"))
        self.learn_year_comboBox.setItemText(0, _translate("login", "全部"))
        self.learn_year_comboBox.setItemText(1, _translate("login", "第一学年"))
        self.learn_year_comboBox.setItemText(2, _translate("login", "第二学年"))
        self.learn_year_comboBox.setItemText(3, _translate("login", "第三学年"))
        self.learn_year_comboBox.setItemText(4, _translate("login", "第四学年"))
        self.stu_id_label.setText(_translate("login", "学号："))
    
    def show_stu_spec_grade(self):
        self.stu_grad_tableWidget.setRowCount(0)
        stu_id=int(self.stu_id_lineEdit.text())
        learn_seme=self.learn_sem_comboBox.currentText()
        learn_year=self.learn_year_comboBox.currentText()
        print("stuid:{} learn_seme:{} and learn_year:{}".format(stu_id,learn_seme,learn_year))
        db_stu_self_grades=pymysql.connect(host="127.0.0.1",user="student",password="123456",database="student_status_information")
        cursor=db_stu_self_grades.cursor()
        if learn_seme=="全部" and learn_year=="全部":
            cursor.execute("select * from stu_year_grades where stu_id=%s",stu_id)
        elif learn_seme=="全部":
            cursor.execute("select * from stu_year_grades where stu_id=%s and learn_year='%s'"%(stu_id,learn_year))
        elif learn_year=="全部":
            cursor.execute("select * from stu_year_grades where stu_id=%s and learn_seme='%s'"%(stu_id,learn_seme))
        else:
            cursor.execute("select * from stu_year_grades where stu_id=%s and learn_seme='%s' and learn_year='%s'"%(stu_id,learn_seme,learn_year))
        results=cursor.fetchall()
        table_rowcount=0
        data_rowcount=len(results)
        print("------------------------test---------------------")
        print(results)
        table_rowcount=0
        data_rowcount=len(results)
        print("length of data:{}".format(data_rowcount))
        if results is not None:
            if table_rowcount<data_rowcount:
                for result in results:
                    self.stu_grad_tableWidget.insertRow(table_rowcount)
                    self.stu_grad_tableWidget.setItem(table_rowcount,0,QtWidgets.QTableWidgetItem(str(result[0])))
                    self.stu_grad_tableWidget.setItem(table_rowcount,1,QtWidgets.QTableWidgetItem(result[1]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,2,QtWidgets.QTableWidgetItem(result[2]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,3,QtWidgets.QTableWidgetItem(result[3]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,4,QtWidgets.QTableWidgetItem(result[4]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,5,QtWidgets.QTableWidgetItem(result[5]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,6,QtWidgets.QTableWidgetItem(str(result[6])))
                    table_rowcount+=1
            db_stu_self_grades.close()
        else:
            Error_msg_stu_info=QtWidgets.QMessageBox()
            Error_msg_stu_info.setText("获取个人信息异常")
            Error_msg_stu_info.show()

        

    def show_stu_all_grades(self):
        self.stu_grad_tableWidget.setRowCount(0)
        stu_id=self.stu_id_lineEdit.text()
        db_stu_self_grades=pymysql.connect(host="127.0.0.1",user="student",password="123456",database="student_status_information")
        cursor=db_stu_self_grades.cursor()
        cursor.execute("select * from stu_year_grades where stu_id =%s",stu_id)
        results=cursor.fetchall()
        print(results)
        table_rowcount=0
        data_rowcount=len(results)
        print("length of data:{}".format(data_rowcount))
        if results is not None:
            if table_rowcount<data_rowcount:
                for result in results:
                    self.stu_grad_tableWidget.insertRow(table_rowcount)
                    self.stu_grad_tableWidget.setItem(table_rowcount,0,QtWidgets.QTableWidgetItem(str(result[0])))
                    self.stu_grad_tableWidget.setItem(table_rowcount,1,QtWidgets.QTableWidgetItem(result[1]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,2,QtWidgets.QTableWidgetItem(result[2]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,3,QtWidgets.QTableWidgetItem(result[3]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,4,QtWidgets.QTableWidgetItem(result[4]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,5,QtWidgets.QTableWidgetItem(result[5]))
                    self.stu_grad_tableWidget.setItem(table_rowcount,6,QtWidgets.QTableWidgetItem(str(result[6])))
                    table_rowcount+=1
            db_stu_self_grades.close()
        else:
            Error_msg_stu_info=QtWidgets.QMessageBox()
            Error_msg_stu_info.setText("获取个人信息异常")
            Error_msg_stu_info.show()
        

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_login()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())